zuul:
  ignoredPatterns: /login
  routes:
    module-service:
      path: /**
      service-id: security-service


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
  instance:
    hostname: localhost
    
server:
  port: 8079
  
spring:
  application:
    name: gateway-service    

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000   

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

  