zuul:
  ignored-patterns: /api-docs/
  routes:
    module-service:
      path: /module/**
      service-id: module-service
    user-service:
      path: /users/**
      service-id: user-service
      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
    
server:
  port: 8083
  
spring:
  application:
    name: security-service

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000   

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
   
swagger:
  gateway:
    service-id: gateway-service
    prefix: /api
  paramters:
    token:
      description: This is a security token
      in: header
      required: false
      type: string

